services:
  env-manager:
    build: .
    image: env-manager:latest
    container_name: env-manager
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DEPLOY_ROOT: /deploy
      DATA_DIR: /app/data
      DEPLOY_HOST_ROOT: ${DEPLOY_HOST_PATH:-/home/kevine/deploy}
    volumes:
      - ${DEPLOY_HOST_PATH:-/home/kevine/deploy}:/deploy:rw
      # Persistance du JSON généré entre les redémarrages.
      - envmgr_data:/app/data
      # === Module Infrastructure ===
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GIT_SSH_KEY_HOST:-./infra_deploy_key}:/keys/deploy_key:ro
    networks:
      - web

networks:
  web:
    external: true

volumes:
  envmgr_data:
